-- Seed data for E-Commerce Platform
-- Note: Passwords are hashed using Werkzeug's generate_password_hash
-- Default password for admin: admin123
-- Default password for user: user123

-- Insert admin user (password: admin123)
-- Password hash for 'admin123': pbkdf2:sha256:260000$... (will be generated by seed.py)
INSERT INTO users (name, email, password_hash, phone, role) VALUES
('Admin User', 'admin@example.com', 'pbkdf2:sha256:260000$PLACEHOLDER', '1234567890', 'admin');

-- Insert regular user (password: user123)
INSERT INTO users (name, email, password_hash, phone, role) VALUES
('Test User', 'user@example.com', 'pbkdf2:sha256:260000$PLACEHOLDER', '0987654321', 'user');

-- Insert categories
INSERT INTO categories (name, slug) VALUES
('Electronics', 'electronics'),
('Clothing', 'clothing'),
('Books', 'books'),
('Home & Garden', 'home-garden'),
('Sports', 'sports');

-- Insert sample products
INSERT INTO products (category_id, name, description, price, stock) VALUES
(1, 'Smartphone', 'Latest smartphone with advanced features', 599.99, 50),
(1, 'Laptop', 'High-performance laptop for work and gaming', 1299.99, 30),
(2, 'T-Shirt', 'Comfortable cotton t-shirt', 19.99, 100),
(2, 'Jeans', 'Classic blue jeans', 49.99, 75),
(3, 'Python Programming Book', 'Learn Python programming from scratch', 39.99, 25),
(3, 'Web Development Guide', 'Complete guide to modern web development', 45.99, 20),
(4, 'Garden Tools Set', 'Complete set of gardening tools', 79.99, 15),
(5, 'Yoga Mat', 'Premium quality yoga mat', 29.99, 40);

-- Note: Product images should be added through the admin interface or seed.py script
-- The seed.py script will handle password hashing and create proper relationships

